cabal-version:      2.4
name:               turbo-prelude
version:            1.5.8.1

synopsis: Alternate prelude and extra library

license-file: LICENSE
license:	  LGPL-3.0-only
author:       loglob
maintainer:   loglob

library
    exposed-modules:
        Control.Attempt
        Control.Mapper
        Data.LargeText
        Data.Or
        Data.RList
        Data.SignedSet
        Data.Span
        Turbo.Cast
        Turbo.Prelude
    build-depends:
        base,
        containers,
        lens,
        mtl,
        primitive,
        template-haskell,
        text,
        transformers,
        vector
    other-modules:
        Data.Internal.ISpan
        Data.Internal.MutSpan
        Data.Internal.Span
        Data.Internal.TextSpan
        Data.Internal.USpan
        Data.Internal.VectorSpan
        Turbo.Extra
        Turbo.ExtraTH
        Turbo.Internal.Classes
        Turbo.Internal.ConsUtils
        Turbo.Internal.MapMaybe
        Turbo.Internal.TH
        Turbo.Operators
        Turbo.OperatorsTH
        Turbo.RootPrelude
    default-extensions:
        BlockArguments
        DataKinds
        LambdaCase
        MagicHash
        NoImplicitPrelude
        PatternSynonyms
        TemplateHaskell
        TypeFamilies
        UnboxedTuples
        ViewPatterns
    ghc-options:
        -Wall
        -Wextra
        -Wno-name-shadowing
    hs-source-dirs:   .
    default-language: GHC2021
