cabal-version:      2.4
name:               turbo-prelude
version:            1.7.1.1

synopsis: Alternate prelude and extra library

license-files: COPYING,
               COPYING.LESSER
license:      LGPL-3.0-only
author:       loglob
maintainer:   loglob

library
    exposed-modules:
        Control.Attempt
        Control.Mapper
        Data.FoldableR
        Data.LargeText
        Data.Or
        Data.RList
        Data.SignedSet
        Data.Span
        Turbo.Cast
        Turbo.Prelude
        Turbo.Operators
    build-depends:
        base,
        containers,
        lens,
        mtl,
        primitive,
        template-haskell,
        text,
        transformers,
        vector
    other-modules:
        Data.Internal.ISpan
        Data.Internal.MutSpan
        Data.Internal.Span
        Data.Internal.TextSpan
        Data.Internal.USpan
        Data.Internal.VectorSpan
        Turbo.Cast.Classes
        Turbo.Cast.TH
        Turbo.Extra
        Turbo.Extra.Fork
        Turbo.Extra.List
        Turbo.Extra.Misc
        Turbo.Extra.Monad
        Turbo.Extra.TH
        Turbo.Internal.Classes
        Turbo.Internal.ConsUtils
        Turbo.Internal.MapMaybe
        Turbo.Internal.Search
        Turbo.Internal.TH
        Turbo.OperatorsTH
        Turbo.RootPrelude
    default-extensions:
        BlockArguments
        DataKinds
        FunctionalDependencies
        LambdaCase
        MagicHash
        NoImplicitPrelude
        PatternSynonyms
        TemplateHaskell
        TypeFamilies
        UnboxedTuples
        ViewPatterns
    ghc-options:
        -Wall
        -Wextra
        -Wno-name-shadowing
        -ddump-splices
    hs-source-dirs:   .
    default-language: GHC2021
